# Site settings
title: Brian Adams 
description: Site Reliability Engineer 
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Brian Adams
user_description: Site Reliability Engineer with a passion for modern CICD tooling like terraform, deployment best practices, data recovery prep, executation, and testing, kubernetes and containers.
user_title: Site Reliability Engineer
email: brian@wayofthesys.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: lsdir
github_username:  autotune
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

